# Generated by Django 5.0.3 on 2024-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minor_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read_status",
            field=models.BooleanField(default=False),
        ),
    ]
