# Generated by Django 5.0.3 on 2024-03-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minor_app", "0003_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
