# Generated by Django 5.0.3 on 2024-03-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minor_app", "0006_remove_report_category_message_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="category",
            field=models.IntegerField(
                choices=[("1", "Concept"), ("2", "Music"), ("999", "Unknown")],
                default="999",
            ),
        ),
    ]
