# Generated by Django 5.0.3 on 2024-03-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minor_app", "0007_alter_message_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Unknown"), (2, "Concept"), (3, "Music")], default=1
            ),
        ),
    ]
